name: Trigger and Wait for Other Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in other repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${TOKEN}" \
            https://api.github.com/repos/umasad087/RepoB/dispatches \
            -d '{"event_type": "triggered-from-other-repo"}'
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for the triggered workflow to complete
        run: |
          sleep 10 # Wait a bit for the workflow to start
          STATUS="queued"
          while [[ "$STATUS" == "queued" || "$STATUS" == "in_progress" ]]
          do
            WORKFLOWS=$(curl -H "Authorization: token ${TOKEN}" \
              "https://api.github.com/repos/umasad087/RepoB/actions/runs?event=repository_dispatch")
            WORKFLOW_ID=$(echo $WORKFLOWS | jq '[.workflow_runs[] | select(.head_branch=="main" and .status!="completed")] | .[0].id')
            STATUS=$(echo $WORKFLOWS | jq -r '.workflow_runs[] | select(.id=='"$WORKFLOW_ID"').status')
            if [[ "$STATUS" == "completed" ]]
            then
              echo "Workflow status: $STATUS."
              break
            fi
            echo "Workflow status: $STATUS. Waiting..."
            sleep 60
          done
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
  jobs:
      needs: wait
      runs-on: ubuntu-latest
      steps:
        - name: build-test
          run: |
            echo "I am building the code.."
          env:
            TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
